events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        location / {
            # ALT: proxy_pass http://frontend:5173;
            proxy_pass http://frontend:80;  
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 2. Task Service (Courses & Topics)
        location /api/courses {
            proxy_pass http://task-service:3000/api/courses;
        }
        location /api/topics {
            proxy_pass http://task-service:3000/api/topics;
        }

        # 3. Exam Service (Exams) 
         location /api/exams {
             proxy_pass http://exam-service:3000/api/exams;
         }

        # 4. Auth Service (Users / Login) 
        # location /api/auth {
        #     proxy_pass http://auth-service:3000/api/auth;
        # }
    }
}